version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: green-haven-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: green-haven-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017
      - SECRET_KEY=your-development-secret-key-change-in-production
      - PAYPAL_MODE=sandbox
      - ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    command: uvicorn server:app --host 0.0.0.0 --port 8001 --reload

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: green-haven-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - REACT_APP_PAYPAL_CLIENT_ID=your_paypal_client_id_here
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn start

volumes:
  mongodb_data: 